site_name: ConfluentFUCCI
site_description: 'A docs test'
site_author: 'Leo Goldstien'
docs_dir: docs/
repo_name: 'leogolds/ConfluentFUCCI'
repo_url: 'https://github.com/leogolds/ConfluentFUCCI'
nav:
    - Home: index.md
    - Walkthroughs:
        - Basic Usage: ../notebooks/walkthrough-1.ipynb

theme:
  name: 'material'

plugins:
  - mkdocs-jupyter