#docker run -it --rm --gpus all -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 -p 9876:9876 leogold/confluentfucci:latest

services:
  confluentfucci:
    image: leogold/confluentfucci:latest
    # env_file:
    #   - .env
    ports:
      - "8080:8080"
      - "9876:9876"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/data/user_data
      - .:/data/models/user_models

#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]

#  test:
#    image: pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime
#    command: nvidia-smi
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
