services:
  confluentfucci:
    image: leogold/confluentfucci:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "9876:9876"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# Uncomment below to mount user data
#      - "${DATA_PATH}:/data/user_data"
#      - "${MODEL_PATH}:/data/models/user_models"
# Uncomment below to enable GPU (CUDA) acceleration on compatible devices
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]


